### ISSUE TITLE
Neue Ebene

### ISSUE THREAD

**Issue by mlue00** [hitobito/hitobito_sbv#123]
Als Vizepräsident des BKMV, einem Unterverein des SBV, wünsche ich mir unterhalb der Regionalverbände eine neue Ebene, damit die Kreise innerhalb der Regionalverbände ebenfalls korrekt erfasst werden können. 
Neu soll es unterhalb der Regionalverbände eine Ebene mit dem Namen "Kreise" geben.

# Mockup

![image](https://user-images.githubusercontent.com/69250571/205012722-564adb67-b7e7-4cd1-b070-134432db255a.png)

# Tech-Spec

- Wir ermöglichen es nur, Kreise zu erstellen. Die eigentlichen Kreise erstellt dann der SBV selber und migriert die bestehenden Gruppen, sobald das ermöglicht ist.
- Kreise sollen für alle Gruppen verfügbar sein.
- Kreise kommen zu den Vereinen hinzu und ersetzen diese nicht. Vereine können weiterhin direkt an Regionalverbänden hängen, oder in Kreisen drin.
- Innerhalb der Kreise gibt es die gleichen Rollen wie bei den Regionalverbänden
- Die Kreise sollen keinen Einfluss auf die SUISA-Meldungen haben
- Optional: Eine Übersicht für die Kreise der SUISA-Listen ihrer untergestellten Vereine
- Unvorhersehbare Auswirkungen an verschiedenen Orten haben, insbesondere in den SBV-spezifischen Features wie Suisa-Meldungen und Musikfeste. 

# ToDo

- [x] Neuer Gruppentyp "Kreis", `layer = true`, mit `children Group::Verein`
  - [x] Gleiche Rollen wie in Regionalverband
- [x] Zusätzlich auch Gruppentypen `Group::KreisGeschaeftsstelle`, `Group::KreisVorstand`, `Group::KreisKontakte` und `Group::KreisMusikkommission` erstellen, analog zu den Untergruppen von `Group::Regionalverband`
  - [x] Gleiche Rollen wie in den jeweiligen Gruppen des Regionalverbands
- [x] Development Seeds ergänzen
- [x] Durchklicken um zu überprüfen ob die SUISA-Übersicht funktioniert, oder ob da etwas deaktiviert werden muss (entsprechend entstehender Aufwand wäre zusätzlich zu verrechnen)

**Comment by carlobeltrame** [comment]
@betsim braucht ihr in einem Kreis auch Gruppentypen für Geschäftsstelle, Vorstand, Kontakte und Musikkommission mit denselben Rollen wie bei Regionalverbänden? Oder sollen wir diese weglassen und nur die Rollen Administrator und SUISA-Admin direkt auf einem Kreis definieren?

**Comment by betsim** [comment]
> @betsim braucht ihr in einem Kreis auch Gruppentypen für Geschäftsstelle, Vorstand, Kontakte und Musikkommission mit denselben Rollen wie bei Regionalverbänden? Oder sollen wir diese weglassen und nur die Rollen Administrator und SUISA-Admin direkt auf einem Kreis definieren?

Ja, bitte inkl. den selben Gruppentypen wie bei Regionalverbände.
