### ISSUE TITLE
PEOPLE: Pflichtfelder reduzieren

### ISSUE THREAD

**Issue by mlue00** [hitobito/hitobito_sbv#125]
Damit sich vereinsweite Anpassungen an Listen einfacher gestalten, sollen temporär nur noch Vorname und Nachname Pflichtfelder einer Person sein. Die restlichen Felder werden entsprechend optional werden. 
Zu einem späteren Zeitpunkt  werden die Änderungen wieder rückgängig gemacht.
Der Termin hierfür ist noch nicht bekannt.

# Tech-Spec

- [x] Vorname Pflichtfeld
- [x] Nachname Pflichtfeld
- [x] Rest ist optional
  - [x] Geburtsdatum
  - [x] Korrespondenzsprache

# ToDo

- [x] module `Sbv::Person` anpassen
- [x] specs anpassen
- [x] alles in einem Commit machen, damit ein leichter Revert möglich ist
- [x] Micha wegen Release informieren
- [x] Mit angemessener Rolle "durchklicken"

**Comment by kronn** [comment]
Als Version 1.28.41 ausgerollt
