### ISSUE TITLE
MESSAGES: Anpassungen neuer Mail Stack

### ISSUE THREAD

**Issue by mtnstar** [hitobito/hitobito_sbv#129]
Damit auch beim SBV der neue Mailstack genutzt werden kann, muss dieser wie bei der Multitenancy so angepasst werden das dieser mit mehreren Domains mit den Mailinglisten umgehen kann.

# Tech-Spec

- evtl. kann dieses Feature in den Core verschoben werden sodass dieser mit mehreren Domains umgehen kann und es praktisch keine Anpassungen in den Wagons mehr braucht 
- https://github.com/hitobito/hitobito_tenants/blob/master/app/domain/tenants/mailing_lists/bulk_mail/retriever.rb

# ToDo

- [ ] Sicherstellen das #114 gefixt ist und Issue schliessen
- [ ] Mail Stack anpassen damit dieser mit mehreren Domains Umgehen kann (generisch im Core oder im SBV Wagon)
- [ ] ggf. Multitenancy Wagon anpassen falls mehr im Core gelöst
- [ ] Neuen Mailstack auf SBV int/prod aktivieren

**Comment by TheWalkingLeek** [comment]
PR #130 steht

Die restlichen Probleme sind für mich nicht nachzuvollziehen. Die Multitenancy benötigte Anpassungen wegen mehrerer **Datenbanken**, nicht Domains. Daher sollte das hier eigentlich auch kein Problem sein, denn hier besteht nur eine DB

**Comment by TheWalkingLeek** [comment]
https://github.com/hitobito/hitobito_sbv/issues/114#issuecomment-1755030108
